version: '3.8'

services:
  backend:
    build: .
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/authdb
      - JWT_SECRET=mon_secret
    depends_on:
      - mongo
    command: npm run dev

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: